- name: Install docker & docker-compose
  hosts: "{{ variable_host | default('amprocessor_host') }}"
  tasks:
    - name: install docker (only for ubuntu 18 bionic)
      ansible.builtin.shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
        apt update
        apt install -y docker-ce
      args:
        warn: false

    - name: install docker-compose
      ansible.builtin.shell: |
        curl -L https://github.com/docker/compose/releases/download/v2.0.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
      args:
        warn: false

    - name: Check docker, docker-compose
      ansible.builtin.shell: |
        systemctl status docker
        echo ""
        docker -v
        docker-compose -v
      register: output
    - debug: var=output.stdout_lines
