version: '3.2'
services:

  database:
    image: "dreamworkerln/amprocessor-database:${TAG}"
    environment:
      POSTGRES_PASSWORD: gjhUY876787ytuh87gdfzk5
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data

volumes:
  postgres-data:
    external: false