version: "3.2"

#7.9.3
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.9.3"
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "discovery.type=single-node"
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=/.*/"
    ports:
      - "127.0.0.1:9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
    image: "docker.elastic.co/kibana/kibana:7.9.3"
    depends_on:
      - elasticsearch
    ports:
      - "127.0.0.1:5601:5601"

  filebeat:
    image: "docker.elastic.co/beats/filebeat:7.9.3"
    depends_on:
      - elasticsearch
    command: "-environment container -strict.perms=false"
    user: root
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  elasticsearch_data: